import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { ImageGenerationError, type GeneratedImage } from "./types.js";

const extensionFor = (contentType: GeneratedImage["contentType"]): string => ({
  "image/png": "png", "image/jpeg": "jpg", "image/webp": "webp", "image/svg+xml": "svg",
})[contentType];

/** Keeps generated bytes outside the public bundle and exposes only a routed asset URL. */
export class LocalImageAssetStore {
  public constructor(private readonly directory = resolve(process.cwd(), "data", "story-images")) {}
  public async persist(cacheKey: string, image: GeneratedImage): Promise<string> {
    if (!/^[a-f0-9]{16,64}$/i.test(cacheKey)) throw new ImageGenerationError("persistence_failed", "Invalid image cache key");
    try {
      await mkdir(this.directory, { recursive: true });
      const filename = `${cacheKey}.${extensionFor(image.contentType)}`;
      await writeFile(resolve(this.directory, filename), image.bytes, { flag: "w" });
      return `/api/images/assets/${filename}`;
    } catch {
      throw new ImageGenerationError("persistence_failed", "Could not save generated image");
    }
  }
  public pathFor(filename: string): string | null {
    if (!/^[a-f0-9]{16,64}\.(png|jpg|webp|svg)$/i.test(filename)) return null;
    return resolve(this.directory, filename);
  }
}
