import { resolve } from "node:path";
import { LocalAssetStore, type AssetStore, type StoredAsset } from "../storage/index.js";
import { ImageGenerationError, type GeneratedImage } from "./types.js";

const extensionFor = (contentType: GeneratedImage["contentType"]): string => ({
  "image/png": "png", "image/jpeg": "jpg", "image/webp": "webp", "image/svg+xml": "svg",
})[contentType];

const validFilename = (filename: string): boolean => /^[a-f0-9]{16,64}\.(png|jpg|webp|svg)$/i.test(filename);

/**
 * Keeps generated bytes outside the browser bundle while making the backing
 * implementation pluggable. In production the backing store can be a Unity
 * Catalog Volume; the browser always uses this same authenticated API route.
 */
export class StoryImageAssetStore {
  public constructor(
    private readonly store: AssetStore,
    private readonly prefix = "images",
  ) {}

  public async persist(cacheKey: string, image: GeneratedImage): Promise<string> {
    if (!/^[a-f0-9]{16,64}$/i.test(cacheKey)) throw new ImageGenerationError("persistence_failed", "Invalid image cache key");
    const filename = `${cacheKey}.${extensionFor(image.contentType)}`;
    try {
      await this.store.put(this.keyFor(filename), image.bytes, image.contentType);
      return `/api/images/assets/${filename}`;
    } catch {
      throw new ImageGenerationError("persistence_failed", "Could not save generated image");
    }
  }

  public async read(filename: string): Promise<StoredAsset | null> {
    if (!validFilename(filename)) return null;
    return this.store.read(this.keyFor(filename));
  }

  private keyFor(filename: string): string {
    return this.prefix ? `${this.prefix}/${filename}` : filename;
  }
}

/**
 * Compatibility adapter for local development and existing test fixtures.
 * New production code should use StoryImageAssetStore with a shared AssetStore.
 */
export class LocalImageAssetStore extends StoryImageAssetStore {
  public constructor(directory = resolve(process.cwd(), "data", "story-images")) {
    super(new LocalAssetStore(directory), "");
  }
}
