import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { DatabricksOAuthM2MTokenProvider, DatabricksVolumeAssetStore } from "./databricks-volume-asset-store.js";
import { createAssetStoreFromEnvironment } from "./factory.js";
import { LocalAssetStore } from "./local-asset-store.js";
import { AssetStoreError } from "./types.js";

const temporaryDirectories: string[] = [];

async function localStore(): Promise<{ store: LocalAssetStore; directory: string }> {
  const directory = await mkdtemp(join(tmpdir(), "storyverse-asset-store-"));
  temporaryDirectories.push(directory);
  return { store: new LocalAssetStore(directory), directory };
}

function databricksStore(fetcher: typeof fetch): DatabricksVolumeAssetStore {
  return new DatabricksVolumeAssetStore({
    host: "https://workspace.cloud.databricks.com",
    token: "test-databricks-token",
    volumePath: "/Volumes/main/default/storyverse_assets/generated",
    fetch: fetcher,
  });
}

function callUrl(fetcher: ReturnType<typeof vi.fn>): string {
  return String(fetcher.mock.calls[0]?.[0]);
}

function callHeaders(fetcher: ReturnType<typeof vi.fn>): Headers {
  return new Headers(fetcher.mock.calls[0]?.[1]?.headers);
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

describe("LocalAssetStore", () => {
  it("writes, finds, and reads generated bytes inside its configured root", async () => {
    const { store, directory } = await localStore();
    const bytes = new Uint8Array([137, 80, 78, 71]);

    await store.put("images/world-1/cover.png", bytes, "image/png");

    expect(await store.exists("images/world-1/cover.png")).toBe(true);
    await expect(readFile(join(directory, "images", "world-1", "cover.png"))).resolves.toEqual(Buffer.from(bytes));
    await expect(store.read("images/world-1/cover.png")).resolves.toEqual({ bytes, contentType: "image/png" });
    expect(await store.exists("images/world-1/missing.png")).toBe(false);
  });

  it("identifies persisted MP4 trailers when the asset backend reads them later", async () => {
    const { store } = await localStore();
    await store.put("trailers/world-1/chapter-1.mp4", new Uint8Array([0, 0, 0, 24]), "video/mp4");

    await expect(store.read("trailers/world-1/chapter-1.mp4")).resolves.toMatchObject({
      contentType: "video/mp4",
    });
  });

  it("rejects traversal and encoded separator keys before touching storage", async () => {
    const { store } = await localStore();
    for (const key of ["../outside.png", "/absolute.png", "images/../outside.png", "images\\outside.png", "images/%2e%2e/outside.png", "images//outside.png"]) {
      await expect(store.put(key, new Uint8Array([1]), "image/png")).rejects.toMatchObject({ code: "invalid_key" } satisfies Partial<AssetStoreError>);
    }
  });
});

describe("DatabricksVolumeAssetStore", () => {
  it("uses the Files API raw-byte PUT URL and headers without putting the token in the URL", async () => {
    const fetcher = vi.fn<typeof fetch>().mockResolvedValue(new Response(null, { status: 204 }));
    const store = databricksStore(fetcher);
    const bytes = new Uint8Array([1, 2, 3, 4]);

    await store.put("images/world-1/cover.png", bytes, "image/png");

    expect(callUrl(fetcher)).toBe("https://workspace.cloud.databricks.com/api/2.0/fs/files/Volumes/main/default/storyverse_assets/generated/images/world-1/cover.png?overwrite=true");
    expect(callUrl(fetcher)).not.toContain("test-databricks-token");
    expect(fetcher.mock.calls[0]?.[1]).toMatchObject({ method: "PUT" });
    expect(callHeaders(fetcher).get("authorization")).toBe("Bearer test-databricks-token");
    expect(callHeaders(fetcher).get("content-type")).toBe("image/png");
    expect(new Uint8Array(fetcher.mock.calls[0]?.[1]?.body as Uint8Array)).toEqual(bytes);
  });

  it("reads raw bytes and uses HEAD for existence checks", async () => {
    const bytes = new Uint8Array([82, 73, 70, 70]);
    const fetcher = vi.fn<typeof fetch>()
      .mockResolvedValueOnce(new Response(bytes, { status: 200, headers: { "content-type": "audio/wav" } }))
      .mockResolvedValueOnce(new Response(null, { status: 200 }))
      .mockResolvedValueOnce(new Response(null, { status: 404 }));
    const store = databricksStore(fetcher);

    await expect(store.read("narrations/world-1/chapter-1.wav")).resolves.toEqual({ bytes, contentType: "audio/wav" });
    await expect(store.exists("narrations/world-1/chapter-1.wav")).resolves.toBe(true);
    await expect(store.exists("narrations/world-1/missing.wav")).resolves.toBe(false);

    expect(fetcher.mock.calls.map((call) => call[1]?.method)).toEqual(["GET", "HEAD", "HEAD"]);
    expect(callUrl(fetcher)).toBe("https://workspace.cloud.databricks.com/api/2.0/fs/files/Volumes/main/default/storyverse_assets/generated/narrations/world-1/chapter-1.wav");
    expect(callHeaders(fetcher).get("authorization")).toBe("Bearer test-databricks-token");
  });

  it("rejects unsafe keys before issuing a provider call", async () => {
    const fetcher = vi.fn<typeof fetch>();
    const store = databricksStore(fetcher);
    for (const key of ["../secret.wav", "/Volumes/other/secret.wav", "images/../secret.wav", "images/%2Fsecret.wav", "images\\secret.wav"]) {
      await expect(store.exists(key)).rejects.toMatchObject({ code: "invalid_key" } satisfies Partial<AssetStoreError>);
    }
    expect(fetcher).not.toHaveBeenCalled();
  });

  it("converts provider failures into safe errors without provider details", async () => {
    const fetcher = vi.fn<typeof fetch>().mockResolvedValue(new Response('{"message":"token test-databricks-token is invalid"}', { status: 401 }));
    const store = databricksStore(fetcher);

    await expect(store.put("images/world-1/cover.png", new Uint8Array([1]), "image/png")).rejects.toMatchObject({ code: "provider_error", status: 401 } satisfies Partial<AssetStoreError>);
    await store.put("images/world-1/cover.png", new Uint8Array([1]), "image/png").catch((error: unknown) => {
      expect(error).toBeInstanceOf(AssetStoreError);
      expect((error as Error).message).not.toContain("test-databricks-token");
    });
  });

  it("converts network failures into a credential-safe provider error", async () => {
    const fetcher = vi.fn<typeof fetch>().mockRejectedValue(new Error("request failed with token test-databricks-token"));
    const store = databricksStore(fetcher);

    const error = await store.read("narrations/world-1/chapter-1.wav").catch((failure: unknown) => failure);
    expect(error).toMatchObject({ code: "provider_error" } satisfies Partial<AssetStoreError>);
    expect((error as Error).message).not.toContain("test-databricks-token");
  });

  it("uses cached workspace OAuth M2M credentials for multiple Volume operations", async () => {
    const fetcher = vi.fn<typeof fetch>()
      .mockResolvedValueOnce(new Response(JSON.stringify({ access_token: "oauth-access-token", expires_in: 3600 }), { status: 200, headers: { "content-type": "application/json" } }))
      .mockResolvedValueOnce(new Response(null, { status: 200 }))
      .mockResolvedValueOnce(new Response(null, { status: 200 }));
    const tokenProvider = new DatabricksOAuthM2MTokenProvider({
      host: "workspace.cloud.databricks.com",
      clientId: "service-principal-id",
      clientSecret: "service-principal-secret",
      fetch: fetcher,
      now: () => 1_000,
    });
    const store = new DatabricksVolumeAssetStore({
      host: "workspace.cloud.databricks.com",
      volumePath: "/Volumes/main/default/storyverse_assets",
      tokenProvider,
      fetch: fetcher,
    });

    await Promise.all([
      store.exists("images/world-1/cover.png"),
      store.exists("narrations/world-1/chapter-1.wav"),
    ]);

    expect(fetcher).toHaveBeenCalledTimes(3);
    expect(String(fetcher.mock.calls[0]?.[0])).toBe("https://workspace.cloud.databricks.com/oidc/v1/token");
    expect(fetcher.mock.calls[0]?.[1]).toMatchObject({ method: "POST" });
    expect(callHeaders(fetcher).get("authorization")).toBe("Basic c2VydmljZS1wcmluY2lwYWwtaWQ6c2VydmljZS1wcmluY2lwYWwtc2VjcmV0");
    expect(String(fetcher.mock.calls[1]?.[0])).toContain("/api/2.0/fs/files/Volumes/main/default/storyverse_assets/images/world-1/cover.png");
    expect(new Headers(fetcher.mock.calls[1]?.[1]?.headers).get("authorization")).toBe("Bearer oauth-access-token");
    expect(new Headers(fetcher.mock.calls[2]?.[1]?.headers).get("authorization")).toBe("Bearer oauth-access-token");
  });

  it("refreshes a rejected OAuth token once without exposing client credentials", async () => {
    const fetcher = vi.fn<typeof fetch>()
      .mockResolvedValueOnce(new Response(JSON.stringify({ access_token: "first-token", expires_in: 3600 }), { status: 200, headers: { "content-type": "application/json" } }))
      .mockResolvedValueOnce(new Response(null, { status: 401 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ access_token: "second-token", expires_in: 3600 }), { status: 200, headers: { "content-type": "application/json" } }))
      .mockResolvedValueOnce(new Response(null, { status: 204 }));
    const tokenProvider = new DatabricksOAuthM2MTokenProvider({
      host: "workspace.cloud.databricks.com",
      clientId: "test-client",
      clientSecret: "test-secret-never-in-errors",
      fetch: fetcher,
    });
    const store = new DatabricksVolumeAssetStore({
      host: "workspace.cloud.databricks.com",
      volumePath: "/Volumes/main/default/storyverse_assets",
      tokenProvider,
      fetch: fetcher,
    });

    await expect(store.put("images/world-1/cover.png", new Uint8Array([1]), "image/png")).resolves.toBeUndefined();

    expect(fetcher).toHaveBeenCalledTimes(4);
    expect(new Headers(fetcher.mock.calls[1]?.[1]?.headers).get("authorization")).toBe("Bearer first-token");
    expect(new Headers(fetcher.mock.calls[3]?.[1]?.headers).get("authorization")).toBe("Bearer second-token");
  });

  it("contains OAuth credential and provider-response details on token failures", async () => {
    const fetcher = vi.fn<typeof fetch>().mockResolvedValue(new Response('{"error":"test-client-secret must not leak"}', { status: 401 }));
    const provider = new DatabricksOAuthM2MTokenProvider({
      host: "workspace.cloud.databricks.com",
      clientId: "test-client-id",
      clientSecret: "test-client-secret",
      fetch: fetcher,
    });

    const error = await provider.getAccessToken().catch((failure: unknown) => failure);

    expect(error).toMatchObject({ code: "provider_error", status: 401 } satisfies Partial<AssetStoreError>);
    expect((error as Error).message).not.toContain("test-client-secret");
  });
});

describe("createAssetStoreFromEnvironment", () => {
  it("defaults to a local store and selects Databricks with either static or OAuth M2M credentials", async () => {
    expect(createAssetStoreFromEnvironment({ environment: {}, localDirectory: "/tmp/storyverse-assets" })).toBeInstanceOf(LocalAssetStore);
    expect(createAssetStoreFromEnvironment({
      environment: {
        STORYVERSE_ASSET_STORAGE: "databricks",
        DATABRICKS_HOST: "workspace.cloud.databricks.com",
        DATABRICKS_TOKEN: "test-databricks-token",
        DATABRICKS_VOLUME_PATH: "/Volumes/main/default/storyverse_assets",
      },
      fetch: vi.fn<typeof fetch>(),
    })).toBeInstanceOf(DatabricksVolumeAssetStore);
    const fetcher = vi.fn<typeof fetch>()
      .mockResolvedValueOnce(new Response(JSON.stringify({ access_token: "oauth-access-token", expires_in: 3600 }), { status: 200, headers: { "content-type": "application/json" } }))
      .mockResolvedValueOnce(new Response(null, { status: 200 }));
    const oauthStore = createAssetStoreFromEnvironment({
      environment: {
        STORYVERSE_ASSET_STORAGE: "databricks-volume",
        DATABRICKS_HOST: "workspace.cloud.databricks.com",
        DATABRICKS_CLIENT_ID: "service-principal-id",
        DATABRICKS_CLIENT_SECRET: "service-principal-secret",
        DATABRICKS_VOLUME_PATH: "/Volumes/main/default/storyverse_assets",
      },
      fetch: fetcher,
    });
    expect(oauthStore).toBeInstanceOf(DatabricksVolumeAssetStore);
    await expect(oauthStore.exists("images/world-1/cover.png")).resolves.toBe(true);
    expect(fetcher).toHaveBeenCalledTimes(2);
  });

  it("fails closed for missing Databricks configuration or an unsupported provider", () => {
    expect(() => createAssetStoreFromEnvironment({ environment: { STORYVERSE_ASSET_STORAGE: "databricks" } })).toThrow(/DATABRICKS_HOST/);
    expect(() => createAssetStoreFromEnvironment({ environment: {
      STORYVERSE_ASSET_STORAGE: "databricks", DATABRICKS_HOST: "workspace.cloud.databricks.com",
      DATABRICKS_VOLUME_PATH: "/Volumes/main/default/storyverse_assets", DATABRICKS_CLIENT_ID: "only-one-credential",
    } })).toThrow(/both DATABRICKS_CLIENT_ID and DATABRICKS_CLIENT_SECRET/);
    expect(() => createAssetStoreFromEnvironment({ environment: {
      STORYVERSE_ASSET_STORAGE: "databricks", DATABRICKS_HOST: "workspace.cloud.databricks.com",
      DATABRICKS_VOLUME_PATH: "/Volumes/main/default/storyverse_assets", DATABRICKS_TOKEN: "legacy-token",
      DATABRICKS_CLIENT_ID: "service-principal-id", DATABRICKS_CLIENT_SECRET: "service-principal-secret",
    } })).toThrow(/either DATABRICKS_TOKEN/);
    expect(() => createAssetStoreFromEnvironment({ environment: {
      STORYVERSE_ASSET_STORAGE: "databricks", DATABRICKS_HOST: "workspace.cloud.databricks.com",
      DATABRICKS_VOLUME_PATH: "/Volumes/main/default/storyverse_assets", DATABRICKS_CLIENT_ID: " service-principal-id",
      DATABRICKS_CLIENT_SECRET: "service-principal-secret",
    } })).toThrow(/DATABRICKS_CLIENT_ID/);
    expect(() => createAssetStoreFromEnvironment({ environment: { STORYVERSE_ASSET_STORAGE: "s3" } })).toThrow(/STORYVERSE_ASSET_STORAGE/);
  });
});
